[default]
fbusername = "username"
fbuserpassword = "password"
headless = "--headless"
tessdata_dir_config = '--tessdata-dir "./tessdata"'
group_targets = ["2065219296931017","589622428215800"]
fanpage_targets = ["twherohan","HGU.tw"]
data_path = "./data"